# Generated by Django 5.0.14 on 2026-04-25 12:23

import admin_portal.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_portal", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalBreederProfile",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bio", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_level",
                    models.CharField(blank=True, default="none", max_length=20),
                ),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "business_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("business_address", models.TextField(blank=True, null=True)),
                ("has_certified_lineage", models.BooleanField(default=False)),
                ("lineage_documentation_count", models.IntegerField(default=0)),
                ("breeding_records_complete", models.BooleanField(default=False)),
                ("healthy_stock_rate", models.FloatField(blank=True, null=True)),
                ("stock_mortality_rate", models.FloatField(blank=True, null=True)),
                ("disease_reported_rate", models.FloatField(blank=True, null=True)),
                ("local_trust_score", models.FloatField(blank=True, null=True)),
                ("specializations", models.JSONField(blank=True, default=list)),
                (
                    "service_area",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "breeders_breederprofile",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ExternalConsultantProfile",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bio", models.TextField(blank=True)),
                ("admin_status", models.CharField(default="pending", max_length=20)),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "business_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("business_address", models.TextField(blank=True, null=True)),
                (
                    "verification_level",
                    models.CharField(blank=True, default="none", max_length=20),
                ),
                ("credentials", models.JSONField(blank=True, default=list)),
                ("specializations", models.JSONField(blank=True, default=list)),
                ("services_list", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "consultant_consultantprofile",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ExternalUser",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("role", models.CharField(max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "profile_picture",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("verification_documents", models.JSONField(blank=True, default=list)),
                ("current_trust_score", models.FloatField(blank=True, null=True)),
                (
                    "current_regulatory_tier",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("is_at_risk", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_auth_user",
                "managed": False,
            },
        ),
        migrations.AlterModelManagers(
            name="adminuser",
            managers=[
                ("objects", admin_portal.managers.AdminUserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name="adminauditlog",
            new_name="admin_porta_created_ecf84d_idx",
            old_name="admin_porta_created_idx",
        ),
        migrations.RenameIndex(
            model_name="aiaccountreview",
            new_name="admin_porta_subject_a6e3ab_idx",
            old_name="admin_porta_subject_type_idx",
        ),
        migrations.RenameIndex(
            model_name="aiaccountreview",
            new_name="admin_porta_decisio_5b43e0_idx",
            old_name="admin_porta_decision_idx",
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
